### ISSUE TITLE
STEP files for USB adaptor

### ISSUE THREAD

**Issue by YanceyA** [MotorDynamicsLab/Nitehawk-36#1]
Hi, can you provide the STEP file for each top and bottom of the usb adaptor case? I would like to modify the wall thickness in a few areas to print properly with a 0.5mm nozzle.

The following areas are thin and do not slice well. Generally wall thickness should be 1mm to enable good slicing for most 3d printer settings.
![image](https://github.com/MotorDynamicsLab/Nitehawk-36/assets/98492882/76f4e943-e5fd-4742-b649-4677b18b80a6)

**Comment by camerony** [comment]
Step file added
